name: wasm sample devel workflow

on:
  push:
    branches:
    - devel
  
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SKIP_PREFLIGHT_CHECK: true
      REACT_APP_API_URL: https://api.develv3.cryptonets.ai/node/FACE4_2
      REACT_APP_API_URL_WASM: https://api.develv3.cryptonets.ai/node/FACE4_2
      REACT_APP_API_KEY: "00000000000000001962"
      REACT_APP_WASM_MODULE: face_mask
      REACT_APP_SET_CACHE: false
      NPM_TOKEN: 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
      REACT_APP_V3_ENROLL_URL1: https://api.develv3.cryptonets.ai/node/FACE3_1/enroll
      REACT_APP_V3_PREDICT_URL1: https://api.develv3.cryptonets.ai/node/FACE3_1/predict
      REACT_APP_V3_ENROLL_URL2: https://api.develv3.cryptonets.ai/node/FACE3_2/enroll
      REACT_APP_V3_PREDICT_URL2: https://api.develv3.cryptonets.ai/node/FACE3_2/predict
      CI: false

    steps:
        - uses: actions/checkout@v1

        - name: Install dependencies
          working-directory: ./wasm_module
          run: npm install

        - name: Build
          working-directory: ./wasm_module
          run: npm run build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: ./wasm_module/build
            bucket: ${{ secrets.S3_BUCKET }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: / *
